"""
MetaRecall — Visual Demo
=========================
Generates a visual summary of the Trust-Aware Associative Retrieval
process. It shows the original image, the 2048-dimensional corrupted
embedding, the Trust Heatmap generated by the MetaRecall Engine,
and the retrieval results for both the Baseline and MetaRecall systems.

Run:
    python visualize_demo.py
"""
import argparse
import io
import os
import pickle
import numpy as np
import matplotlib.pyplot as plt
import torch
import torchvision.datasets as ds

CLASS_NAMES = [
    "airplane", "automobile", "bird", "cat",
    "deer",     "dog",        "frog", "horse",
    "ship",     "truck",
]
N_CLASSES   = 10
DATASET_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "dataset")

def _load_cpu(path: str) -> torch.Tensor:
    class _CpuUnpickler(pickle.Unpickler):
        def find_class(self, module, name):
            if module == "torch.storage" and name == "_load_from_bytes":
                return lambda b: torch.load(
                    io.BytesIO(b), map_location="cpu", weights_only=False
                )
            return super().find_class(module, name)
    with open(path, "rb") as f:
        return _CpuUnpickler(f).load()

def load_data():
    train_X = _load_cpu(os.path.join(DATASET_DIR, "train_features_c10.p")).numpy().astype(np.float32)
    train_y = _load_cpu(os.path.join(DATASET_DIR, "train_labels_c10.p")).numpy().astype(np.int32)
    test_X  = _load_cpu(os.path.join(DATASET_DIR, "test_features_c10.p")).numpy().astype(np.float32)
    test_y  = _load_cpu(os.path.join(DATASET_DIR, "test_labels_c10.p")).numpy().astype(np.int32)
    return train_X, train_y, test_X, test_y

class MemoryBank:
    def __init__(self, train_X: np.ndarray, train_y: np.ndarray):
        D = train_X.shape[1]
        self.proto_raw = np.zeros((N_CLASSES, D), dtype=np.float32)
        self.proto_nrm = np.zeros((N_CLASSES, D), dtype=np.float32)

        for c in range(N_CLASSES):
            p = train_X[train_y == c].mean(axis=0)
            self.proto_raw[c] = p
            self.proto_nrm[c] = p / (np.linalg.norm(p) + 1e-12)

    def retrieve_baseline(self, q_raw: np.ndarray) -> int:
        qn = q_raw / (np.linalg.norm(q_raw) + 1e-12)
        return int(np.argmax(self.proto_nrm @ qn))

    def retrieve_trust(self, q_raw: np.ndarray, pi: np.ndarray) -> int:
        qn = q_raw / (np.linalg.norm(q_raw) + 1e-12)
        qw = pi * qn
        qw /= np.linalg.norm(qw) + 1e-12
        pw = self.proto_nrm * pi[None, :]
        return int(np.argmax(pw @ qw))

def corrupt(vec: np.ndarray, noise_std: float, rng: np.random.Generator) -> np.ndarray:
    out = vec + rng.normal(0.0, noise_std, size=len(vec)).astype(np.float32)
    out = np.clip(out, 0.0, None)
    return out

def predict_precision_magnitude(query: np.ndarray) -> np.ndarray:
    pi = query + 0.1
    pi = np.clip(pi, 0.1, 10.0)
    return pi / pi.mean()

def run_visual_demo(noise_std=1.5, seed=42):
    print("Loading data...")
    train_X, train_y, test_X, test_y = load_data()
    bank = MemoryBank(train_X, train_y)
    
    print("Loading CIFAR-10 images...")
    cifar_test = ds.CIFAR10(root='./cifar10_raw', train=False, download=True)
    cifar_train = ds.CIFAR10(root='./cifar10_raw', train=True, download=True)
    
    rng = np.random.default_rng(seed)
    
    # Find a query where MetaRecall succeeds and Baseline fails
    print("Finding a good example query...")
    best_qi = None
    for qi in range(100):
        orig = test_X[qi]
        true = int(test_y[qi])
        q_c = corrupt(orig, noise_std, rng)
        
        b_pred = bank.retrieve_baseline(q_c)
        pi = predict_precision_magnitude(q_c)
        t_pred = bank.retrieve_trust(q_c, pi)
        
        if b_pred != true and t_pred == true:
            best_qi = qi
            break
            
    if best_qi is None:
        best_qi = 0
        orig = test_X[best_qi]
        true = int(test_y[best_qi])
        q_c = corrupt(orig, noise_std, rng)
        b_pred = bank.retrieve_baseline(q_c)
        pi = predict_precision_magnitude(q_c)
        t_pred = bank.retrieve_trust(q_c, pi)
        
    print(f"Selected Query {best_qi} (True Class: {CLASS_NAMES[true]})")
    
    # Get representative images for the retrieved classes
    orig_img = np.array(cifar_test[best_qi][0])
    
    def get_rep_image(class_idx):
        for i in range(len(cifar_train)):
            if cifar_train[i][1] == class_idx:
                return np.array(cifar_train[i][0])
                
    base_img = get_rep_image(b_pred)
    trust_img = get_rep_image(t_pred)
    
    # Plotting
    fig = plt.figure(figsize=(15, 10))
    fig.suptitle('MetaRecall: Trust-Aware Associative Retrieval under Severe Corruption', fontsize=18, fontweight='bold')
    
    # Top row: Original Image, Embedding, Corrupted Embedding
    ax1 = plt.subplot(2, 4, 1)
    ax1.imshow(orig_img)
    ax1.set_title(f'Original Image\nClass: {CLASS_NAMES[true]}', fontsize=12)
    ax1.axis('off')
    
    ax2 = plt.subplot(2, 4, 2)
    ax2.plot(orig, color='blue', alpha=0.7)
    ax2.set_title('Clean ResNet-50\nEmbedding (2048-d)', fontsize=12)
    ax2.set_xticks([]); ax2.set_yticks([])
    
    ax3 = plt.subplot(2, 4, 3)
    ax3.plot(q_c, color='red', alpha=0.7)
    ax3.set_title(f'Corrupted Embedding\n(Noise σ={noise_std} + ReLU)', fontsize=12)
    ax3.set_xticks([]); ax3.set_yticks([])
    
    # Trust Heatmap
    ax4 = plt.subplot(2, 4, 4)
    # Reshape Pi to a 32x64 2D map for visualization
    pi_map = pi.reshape(32, 64)
    im = ax4.imshow(pi_map, cmap='viridis', aspect='auto')
    ax4.set_title('MetaRecall Precision Map\n(Trust Heatmap)', fontsize=12)
    ax4.set_xticks([]); ax4.set_yticks([])
    plt.colorbar(im, ax=ax4, orientation='vertical')
    
    # Bottom row: Baseline Retrieval vs MetaRecall Retrieval
    ax5 = plt.subplot(2, 4, 6)
    ax5.imshow(base_img)
    color = 'green' if b_pred == true else 'red'
    ax5.set_title(f'Baseline Retrieval (Π=I)\nClass: {CLASS_NAMES[b_pred]}', color=color, fontsize=14, fontweight='bold')
    ax5.axis('off')
    
    ax6 = plt.subplot(2, 4, 7)
    ax6.imshow(trust_img)
    color = 'green' if t_pred == true else 'red'
    ax6.set_title(f'MetaRecall Retrieval\nClass: {CLASS_NAMES[t_pred]}', color=color, fontsize=14, fontweight='bold')
    ax6.axis('off')
    
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    save_path = 'metarecall_visual_demo.png'
    plt.savefig(save_path, dpi=150)
    print(f"Visual demo saved successfully to {save_path}")
    
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--noise", type=float, default=1.5)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    run_visual_demo(args.noise, args.seed)
